# Generated by Django 4.2.1 on 2023-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_event_thumbnail_eventimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimages',
            options={'verbose_name_plural': 'Event Images'},
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.FileField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
