# Generated by Django 4.2.1 on 2023-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.FileField(default='', upload_to='team'),
            preserve_default=False,
        ),
    ]
